apiVersion: v1
kind: Service
metadata:
  name: metering-svc
  namespace: hnc-metering
spec:
  selector:
    app: metering-server
  type: ClusterIP
  ports:  
    - port: 8080
      targetPort: 8080
      #name: http
